spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/add_dict_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:pswd}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jwt:
    secret: ${JWT_SECRET:awdksiermpddpvmisdmsjdyedjkfqwrtldoeuifbcnbnmdh} # add real secret in env param in prod
    access-token-expiration: 20m
    refresh-token-expiration: 1d

  user:
    validation-rule:
      login:
        min-length: 2
        max-length: 32
        regex: ^[a-zA-Z0-9_]{${spring.user.validation-rule.login.min-length},${spring.user.validation-rule.login.max-length}}$
      password:
        min-length: 2
        max-length: 64
        regex: ^[a-zA-Z0-9_!#]{${spring.user.validation-rule.password.min-length},${spring.user.validation-rule.password.max-length}}$

server:
  port: 8081

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        engine:
          jdbc:
            batch:
              internal:
                BatchingBatch: TRACE